# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
#
path: ../datasets  # dataset root dir
train: 
    - Combined/Train/images  # train images
val: 
     - Combined/Val/images
test:  # test images (optional)

names:
  0: barrel
  1: fire
  2: smoke